import os
import math
import re
from collections import Counter
import multiprocessing
import matplotlib.pyplot as plt
from concurrent.futures import ThreadPoolExecutor
import csv
import glob
import random

spec_trace=[
    # "traces/spec/401.bzip2-277B.champsimtrace.xz",
    "traces/spec/605.mcf_s-1152B.champsimtrace.xz",
    "traces/spec/605.mcf_s-1536B.champsimtrace.xz",
    "traces/spec/605.mcf_s-1554B.champsimtrace.xz",
    "traces/spec/605.mcf_s-1644B.champsimtrace.xz",
    "traces/spec/605.mcf_s-472B.champsimtrace.xz",
    "traces/spec/605.mcf_s-484B.champsimtrace.xz",
    "traces/spec/605.mcf_s-665B.champsimtrace.xz",
    "traces/spec/605.mcf_s-782B.champsimtrace.xz",
    "traces/spec/605.mcf_s-994B.champsimtrace.xz",
    "traces/spec/403.gcc-17B.champsimtrace.xz",
    "traces/spec/410.bwaves-1963B.champsimtrace.xz",
    "traces/spec/410.bwaves-2097B.champsimtrace.xz",
    "traces/spec/429.mcf-184B.champsimtrace.xz",
    "traces/spec/429.mcf-192B.champsimtrace.xz",
    "traces/spec/429.mcf-217B.champsimtrace.xz",
    "traces/spec/429.mcf-22B.champsimtrace.xz",
    "traces/spec/429.mcf-51B.champsimtrace.xz",
    "traces/spec/433.milc-127B.champsimtrace.xz",
    "traces/spec/433.milc-274B.champsimtrace.xz",
    "traces/spec/433.milc-337B.champsimtrace.xz",
    "traces/spec/434.zeusmp-10B.champsimtrace.xz",
    "traces/spec/436.cactusADM-1804B.champsimtrace.xz",
    "traces/spec/437.leslie3d-134B.champsimtrace.xz",
    "traces/spec/437.leslie3d-149B.champsimtrace.xz",
    "traces/spec/437.leslie3d-232B.champsimtrace.xz",
    "traces/spec/437.leslie3d-265B.champsimtrace.xz",
    "traces/spec/437.leslie3d-271B.champsimtrace.xz",
    "traces/spec/437.leslie3d-273B.champsimtrace.xz",
    "traces/spec/450.soplex-247B.champsimtrace.xz",
    "traces/spec/450.soplex-92B.champsimtrace.xz",
    "traces/spec/459.GemsFDTD-1169B.champsimtrace.xz",
    "traces/spec/459.GemsFDTD-1211B.champsimtrace.xz",
    "traces/spec/459.GemsFDTD-1320B.champsimtrace.xz",
    "traces/spec/459.GemsFDTD-1418B.champsimtrace.xz",
    "traces/spec/459.GemsFDTD-1491B.champsimtrace.xz",
    "traces/spec/459.GemsFDTD-765B.champsimtrace.xz",
    "traces/spec/462.libquantum-1343B.champsimtrace.xz",
    "traces/spec/462.libquantum-714B.champsimtrace.xz",
    "traces/spec/470.lbm-1274B.champsimtrace.xz",
    "traces/spec/471.omnetpp-188B.champsimtrace.xz",
    "traces/spec/473.astar-359B.champsimtrace.xz",
    "traces/spec/473.astar-42B.champsimtrace.xz",
    "traces/spec/481.wrf-1254B.champsimtrace.xz",
    "traces/spec/481.wrf-1281B.champsimtrace.xz",
    "traces/spec/481.wrf-196B.champsimtrace.xz",
    "traces/spec/481.wrf-455B.champsimtrace.xz",
    "traces/spec/481.wrf-816B.champsimtrace.xz",
    "traces/spec/482.sphinx3-1100B.champsimtrace.xz",
    "traces/spec/482.sphinx3-1297B.champsimtrace.xz",
    "traces/spec/482.sphinx3-1395B.champsimtrace.xz",
    "traces/spec/482.sphinx3-1522B.champsimtrace.xz",
    "traces/spec/482.sphinx3-234B.champsimtrace.xz",
    "traces/spec/482.sphinx3-417B.champsimtrace.xz",
    "traces/spec/483.xalancbmk-127B.champsimtrace.xz",
    "traces/spec/602.gcc_s-1850B.champsimtrace.xz",
    "traces/spec/602.gcc_s-2226B.champsimtrace.xz",
    "traces/spec/602.gcc_s-734B.champsimtrace.xz",
    "traces/spec/603.bwaves_s-1740B.champsimtrace.xz",
    "traces/spec/603.bwaves_s-2609B.champsimtrace.xz",
    "traces/spec/603.bwaves_s-2931B.champsimtrace.xz",
    "traces/spec/603.bwaves_s-891B.champsimtrace.xz",    
    "traces/spec/607.cactuBSSN_s-2421B.champsimtrace.xz",
    "traces/spec/607.cactuBSSN_s-3477B.champsimtrace.xz",
    "traces/spec/607.cactuBSSN_s-4004B.champsimtrace.xz",
    "traces/spec/619.lbm_s-2676B.champsimtrace.xz",
    "traces/spec/619.lbm_s-2677B.champsimtrace.xz",
    "traces/spec/619.lbm_s-3766B.champsimtrace.xz",
    "traces/spec/619.lbm_s-4268B.champsimtrace.xz",
    "traces/spec/620.omnetpp_s-141B.champsimtrace.xz",
    "traces/spec/620.omnetpp_s-874B.champsimtrace.xz",
    "traces/spec/621.wrf_s-6673B.champsimtrace.xz",
    "traces/spec/621.wrf_s-8065B.champsimtrace.xz",
    "traces/spec/623.xalancbmk_s-10B.champsimtrace.xz",
    "traces/spec/623.xalancbmk_s-165B.champsimtrace.xz",
    "traces/spec/623.xalancbmk_s-202B.champsimtrace.xz",
    "traces/spec/625.x264_s-20B.champsimtrace.xz",
    "traces/spec/627.cam4_s-490B.champsimtrace.xz",
    "traces/spec/628.pop2_s-17B.champsimtrace.xz",
    "traces/spec/649.fotonik3d_s-10881B.champsimtrace.xz",
    "traces/spec/649.fotonik3d_s-1176B.champsimtrace.xz",
    "traces/spec/649.fotonik3d_s-7084B.champsimtrace.xz",
    "traces/spec/649.fotonik3d_s-8225B.champsimtrace.xz",
    "traces/spec/654.roms_s-1007B.champsimtrace.xz",
    "traces/spec/654.roms_s-1070B.champsimtrace.xz",
    "traces/spec/654.roms_s-1390B.champsimtrace.xz",
    "traces/spec/654.roms_s-1613B.champsimtrace.xz",
    "traces/spec/654.roms_s-293B.champsimtrace.xz",
    "traces/spec/654.roms_s-294B.champsimtrace.xz",
    "traces/spec/654.roms_s-523B.champsimtrace.xz",
    "traces/spec/657.xz_s-2302B.champsimtrace.xz"
]

gap_trace=[
    "traces/gap/sssp-5.trace.gz",
    "traces/gap/bfs-14.trace.gz",
    "traces/gap/sssp-3.trace.gz",
    "traces/gap/cc-14.trace.gz",
    "traces/gap/pr-3.trace.gz",
    "traces/gap/sssp-14.trace.gz",
    "traces/gap/pr-10.trace.gz",
    "traces/gap/cc-5.trace.gz",
    "traces/gap/bc-5.trace.gz",
    "traces/gap/pr-5.trace.gz",
    "traces/gap/bc-3.trace.gz",
    "traces/gap/bfs-3.trace.gz",
    "traces/gap/cc-6.trace.gz",
    "traces/gap/cc-13.trace.gz",
    "traces/gap/sssp-10.trace.gz",
    "traces/gap/bfs-8.trace.gz",
    "traces/gap/bc-0.trace.gz",
    "traces/gap/bfs-10.trace.gz",
    "traces/gap/bc-12.trace.gz",
    "traces/gap/pr-14.trace.gz"
]

cs_trace=[
    "traces/cs/cassandra_phase0_core0.trace.xz",
    "traces/cs/cassandra_phase0_core1.trace.xz",
    "traces/cs/cassandra_phase0_core2.trace.xz",
    "traces/cs/cassandra_phase0_core3.trace.xz",
    "traces/cs/cassandra_phase1_core0.trace.xz",
    "traces/cs/cassandra_phase1_core1.trace.xz",
    "traces/cs/cassandra_phase1_core2.trace.xz",
    "traces/cs/cassandra_phase1_core3.trace.xz",
    "traces/cs/cassandra_phase2_core0.trace.xz",
    "traces/cs/cassandra_phase2_core1.trace.xz",
    "traces/cs/cassandra_phase2_core2.trace.xz",
    "traces/cs/cassandra_phase2_core3.trace.xz",
    "traces/cs/cassandra_phase3_core0.trace.xz",
    "traces/cs/cassandra_phase3_core1.trace.xz",
    "traces/cs/cassandra_phase3_core2.trace.xz",
    "traces/cs/cassandra_phase3_core3.trace.xz",
    "traces/cs/cassandra_phase4_core0.trace.xz",
    "traces/cs/cassandra_phase4_core1.trace.xz",
    "traces/cs/cassandra_phase4_core2.trace.xz",
    "traces/cs/cassandra_phase4_core3.trace.xz",
    "traces/cs/cassandra_phase5_core0.trace.xz",
    "traces/cs/cassandra_phase5_core1.trace.xz",
    "traces/cs/cassandra_phase5_core2.trace.xz",
    "traces/cs/cassandra_phase5_core3.trace.xz",
    "traces/cs/classification_phase0_core0.trace.xz",
    "traces/cs/classification_phase0_core1.trace.xz",
    "traces/cs/classification_phase0_core2.trace.xz",
    "traces/cs/classification_phase0_core3.trace.xz",
    "traces/cs/classification_phase1_core0.trace.xz",
    "traces/cs/classification_phase1_core1.trace.xz",
    "traces/cs/classification_phase1_core2.trace.xz",
    "traces/cs/classification_phase1_core3.trace.xz",
    "traces/cs/classification_phase2_core0.trace.xz",
    "traces/cs/classification_phase2_core1.trace.xz",
    "traces/cs/classification_phase2_core2.trace.xz",
    "traces/cs/classification_phase2_core3.trace.xz",
    "traces/cs/classification_phase3_core0.trace.xz",
    "traces/cs/classification_phase3_core1.trace.xz",
    "traces/cs/classification_phase3_core2.trace.xz",
    "traces/cs/classification_phase3_core3.trace.xz",
    "traces/cs/classification_phase4_core0.trace.xz",
    "traces/cs/classification_phase4_core1.trace.xz",
    "traces/cs/classification_phase4_core2.trace.xz",
    "traces/cs/classification_phase4_core3.trace.xz",
    "traces/cs/classification_phase5_core0.trace.xz",
    "traces/cs/classification_phase5_core1.trace.xz",
    "traces/cs/classification_phase5_core2.trace.xz",
    "traces/cs/classification_phase5_core3.trace.xz",
    "traces/cs/cloud9_phase0_core0.trace.xz",
    "traces/cs/cloud9_phase0_core1.trace.xz",
    "traces/cs/cloud9_phase0_core2.trace.xz",
    "traces/cs/cloud9_phase0_core3.trace.xz",
    "traces/cs/cloud9_phase1_core0.trace.xz",
    "traces/cs/cloud9_phase1_core1.trace.xz",
    "traces/cs/cloud9_phase1_core2.trace.xz",
    "traces/cs/cloud9_phase1_core3.trace.xz",
    "traces/cs/cloud9_phase2_core0.trace.xz",
    "traces/cs/cloud9_phase2_core1.trace.xz",
    "traces/cs/cloud9_phase2_core2.trace.xz",
    "traces/cs/cloud9_phase2_core3.trace.xz",
    "traces/cs/cloud9_phase3_core0.trace.xz",
    "traces/cs/cloud9_phase3_core1.trace.xz",
    "traces/cs/cloud9_phase3_core2.trace.xz",
    "traces/cs/cloud9_phase3_core3.trace.xz",
    "traces/cs/cloud9_phase4_core0.trace.xz",
    "traces/cs/cloud9_phase4_core1.trace.xz",
    "traces/cs/cloud9_phase4_core2.trace.xz",
    "traces/cs/cloud9_phase4_core3.trace.xz",
    "traces/cs/cloud9_phase5_core0.trace.xz",
    "traces/cs/cloud9_phase5_core1.trace.xz",
    "traces/cs/cloud9_phase5_core2.trace.xz",
    "traces/cs/cloud9_phase5_core3.trace.xz",
    "traces/cs/nutch_phase0_core0.trace.xz",
    "traces/cs/nutch_phase0_core1.trace.xz",
    "traces/cs/nutch_phase0_core2.trace.xz",
    "traces/cs/nutch_phase0_core3.trace.xz",
    "traces/cs/nutch_phase1_core0.trace.xz",
    "traces/cs/nutch_phase1_core1.trace.xz",
    "traces/cs/nutch_phase1_core2.trace.xz",
    "traces/cs/nutch_phase1_core3.trace.xz",
    "traces/cs/nutch_phase2_core0.trace.xz",
    "traces/cs/nutch_phase2_core1.trace.xz",
    "traces/cs/nutch_phase2_core2.trace.xz",
    "traces/cs/nutch_phase2_core3.trace.xz",
    "traces/cs/nutch_phase3_core0.trace.xz",
    "traces/cs/nutch_phase3_core1.trace.xz",
    "traces/cs/nutch_phase3_core2.trace.xz",
    "traces/cs/nutch_phase3_core3.trace.xz",
    "traces/cs/nutch_phase4_core0.trace.xz",
    "traces/cs/nutch_phase4_core1.trace.xz",
    "traces/cs/nutch_phase4_core2.trace.xz",
    "traces/cs/nutch_phase4_core3.trace.xz",
    "traces/cs/nutch_phase5_core0.trace.xz",
    "traces/cs/nutch_phase5_core1.trace.xz",
    "traces/cs/nutch_phase5_core2.trace.xz",
    "traces/cs/nutch_phase5_core3.trace.xz",
    "traces/cs/streaming_phase0_core0.trace.xz",
    "traces/cs/streaming_phase0_core1.trace.xz",
    "traces/cs/streaming_phase0_core2.trace.xz",
    "traces/cs/streaming_phase0_core3.trace.xz",
    "traces/cs/streaming_phase1_core0.trace.xz",
    "traces/cs/streaming_phase1_core1.trace.xz",
    "traces/cs/streaming_phase1_core2.trace.xz",
    "traces/cs/streaming_phase1_core3.trace.xz",
    "traces/cs/streaming_phase2_core0.trace.xz",
    "traces/cs/streaming_phase2_core1.trace.xz",
    "traces/cs/streaming_phase2_core2.trace.xz",
    "traces/cs/streaming_phase2_core3.trace.xz",
    "traces/cs/streaming_phase3_core0.trace.xz",
    "traces/cs/streaming_phase3_core1.trace.xz",
    "traces/cs/streaming_phase3_core2.trace.xz",
    "traces/cs/streaming_phase3_core3.trace.xz",
    "traces/cs/streaming_phase4_core0.trace.xz",
    "traces/cs/streaming_phase4_core1.trace.xz",
    "traces/cs/streaming_phase4_core2.trace.xz",
    "traces/cs/streaming_phase4_core3.trace.xz",
    "traces/cs/streaming_phase5_core0.trace.xz",
    "traces/cs/streaming_phase5_core1.trace.xz",
    "traces/cs/streaming_phase5_core2.trace.xz",
    "traces/cs/streaming_phase5_core3.trace.xz"

]

ligra_trace=[
    "traces/ligra/ligra_BFSCC.com-lj.ungraph.gcc_6.3.0_O3.drop_18750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_CF.com-lj.ungraph.gcc_6.3.0_O3.drop_184750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_PageRankDelta.com-lj.ungraph.gcc_6.3.0_O3.drop_24500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_PageRank.com-lj.ungraph.gcc_6.3.0_O3.drop_79500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Triangle.com-lj.ungraph.gcc_6.3.0_O3.drop_10250M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_MIS.com-lj.ungraph.gcc_6.3.0_O3.drop_11000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFSCC.com-lj.ungraph.gcc_6.3.0_O3.drop_5000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFSCC.com-lj.ungraph.gcc_6.3.0_O3.drop_15500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_PageRank.com-lj.ungraph.gcc_6.3.0_O3.drop_60750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Components-Shortcut.com-lj.ungraph.gcc_6.3.0_O3.drop_5000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFS.com-lj.ungraph.gcc_6.3.0_O3.drop_20250M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Radii.com-lj.ungraph.gcc_6.3.0_O3.drop_32000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_CF.com-lj.ungraph.gcc_6.3.0_O3.drop_2500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_PageRank.com-lj.ungraph.gcc_6.3.0_O3.drop_21750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_PageRank.com-lj.ungraph.gcc_6.3.0_O3.drop_18500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Radii.com-lj.ungraph.gcc_6.3.0_O3.drop_18000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFSCC.com-lj.ungraph.gcc_6.3.0_O3.drop_17000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Components-Shortcut.com-lj.ungraph.gcc_6.3.0_O3.drop_17000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_MIS.com-lj.ungraph.gcc_6.3.0_O3.drop_15750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BC.com-lj.ungraph.gcc_6.3.0_O3.drop_5000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Components.com-lj.ungraph.gcc_6.3.0_O3.drop_23750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BC.com-lj.ungraph.gcc_6.3.0_O3.drop_15750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFS-Bitvector.com-lj.ungraph.gcc_6.3.0_O3.drop_23000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Components.com-lj.ungraph.gcc_6.3.0_O3.drop_750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Radii.com-lj.ungraph.gcc_6.3.0_O3.drop_5000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BC.com-lj.ungraph.gcc_6.3.0_O3.drop_26750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_PageRankDelta.com-lj.ungraph.gcc_6.3.0_O3.drop_6000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Radii.com-lj.ungraph.gcc_6.3.0_O3.drop_36000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFSCC.com-lj.ungraph.gcc_6.3.0_O3.drop_750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Components-Shortcut.com-lj.ungraph.gcc_6.3.0_O3.drop_21000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Components.com-lj.ungraph.gcc_6.3.0_O3.drop_3500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Radii.com-lj.ungraph.gcc_6.3.0_O3.drop_750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_PageRank.com-lj.ungraph.gcc_6.3.0_O3.drop_10750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BellmanFord.com-lj.ungraph.gcc_6.3.0_O3.drop_33750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Components-Shortcut.com-lj.ungraph.gcc_6.3.0_O3.drop_750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_PageRankDelta.com-lj.ungraph.gcc_6.3.0_O3.drop_1250M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFS.com-lj.ungraph.gcc_6.3.0_O3.drop_17000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BC.com-lj.ungraph.gcc_6.3.0_O3.drop_500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFS.com-lj.ungraph.gcc_6.3.0_O3.drop_3500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BellmanFord.com-lj.ungraph.gcc_6.3.0_O3.drop_4000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFSCC.com-lj.ungraph.gcc_6.3.0_O3.drop_6750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Components.com-lj.ungraph.gcc_6.3.0_O3.drop_22750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BC.com-lj.ungraph.gcc_6.3.0_O3.drop_17000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFSCC.com-lj.ungraph.gcc_6.3.0_O3.drop_22000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Radii.com-lj.ungraph.gcc_6.3.0_O3.drop_3500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFS-Bitvector.com-lj.ungraph.gcc_6.3.0_O3.drop_500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BC.com-lj.ungraph.gcc_6.3.0_O3.drop_11500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BC.com-lj.ungraph.gcc_6.3.0_O3.drop_15500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Triangle.com-lj.ungraph.gcc_6.3.0_O3.drop_25250M.length_8M.champsimtrace.xz",
    "traces/ligra/ligra_MIS.com-lj.ungraph.gcc_6.3.0_O3.drop_750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_PageRank.com-lj.ungraph.gcc_6.3.0_O3.drop_5000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BellmanFord.com-lj.ungraph.gcc_6.3.0_O3.drop_1750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Triangle.com-lj.ungraph.gcc_6.3.0_O3.drop_18000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BellmanFord.com-lj.ungraph.gcc_6.3.0_O3.drop_7500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFS.com-lj.ungraph.gcc_6.3.0_O3.drop_11500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Radii.com-lj.ungraph.gcc_6.3.0_O3.drop_12500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BellmanFord.com-lj.ungraph.gcc_6.3.0_O3.drop_24750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_PageRankDelta.com-lj.ungraph.gcc_6.3.0_O3.drop_24000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BellmanFord.com-lj.ungraph.gcc_6.3.0_O3.drop_14000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFS-Bitvector.com-lj.ungraph.gcc_6.3.0_O3.drop_9750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Components-Shortcut.com-lj.ungraph.gcc_6.3.0_O3.drop_3500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Triangle.com-lj.ungraph.gcc_6.3.0_O3.drop_25000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Triangle.com-lj.ungraph.gcc_6.3.0_O3.drop_750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_PageRankDelta.com-lj.ungraph.gcc_6.3.0_O3.drop_56500M.length_208M.champsimtrace.xz",
    "traces/ligra/ligra_PageRank.com-lj.ungraph.gcc_6.3.0_O3.drop_51000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_MIS.com-lj.ungraph.gcc_6.3.0_O3.drop_5000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_PageRankDelta.com-lj.ungraph.gcc_6.3.0_O3.drop_17000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BC.com-lj.ungraph.gcc_6.3.0_O3.drop_3500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Components-Shortcut.com-lj.ungraph.gcc_6.3.0_O3.drop_22000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFS.com-lj.ungraph.gcc_6.3.0_O3.drop_500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_CF.com-lj.ungraph.gcc_6.3.0_O3.drop_154750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Components.com-lj.ungraph.gcc_6.3.0_O3.drop_15750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Components.com-lj.ungraph.gcc_6.3.0_O3.drop_12500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Triangle.com-lj.ungraph.gcc_6.3.0_O3.drop_3500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFS.com-lj.ungraph.gcc_6.3.0_O3.drop_21500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BellmanFord.com-lj.ungraph.gcc_6.3.0_O3.drop_22250M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Components.com-lj.ungraph.gcc_6.3.0_O3.drop_18000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_CF.com-lj.ungraph.gcc_6.3.0_O3.drop_10750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Radii.com-lj.ungraph.gcc_6.3.0_O3.drop_25000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_PageRank.com-lj.ungraph.gcc_6.3.0_O3.drop_500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFSCC.com-lj.ungraph.gcc_6.3.0_O3.drop_11250M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Triangle.com-lj.ungraph.gcc_6.3.0_O3.drop_6000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFS.com-lj.ungraph.gcc_6.3.0_O3.drop_5000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFS-Bitvector.com-lj.ungraph.gcc_6.3.0_O3.drop_18000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Components.com-lj.ungraph.gcc_6.3.0_O3.drop_6250M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Components.com-lj.ungraph.gcc_6.3.0_O3.drop_5000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_MIS.com-lj.ungraph.gcc_6.3.0_O3.drop_17000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_MIS.com-lj.ungraph.gcc_6.3.0_O3.drop_3500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_MIS.com-lj.ungraph.gcc_6.3.0_O3.drop_21250M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Triangle.com-lj.ungraph.gcc_6.3.0_O3.drop_24000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BellmanFord.com-lj.ungraph.gcc_6.3.0_O3.drop_5500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_PageRankDelta.com-lj.ungraph.gcc_6.3.0_O3.drop_52000M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFS-Bitvector.com-lj.ungraph.gcc_6.3.0_O3.drop_2500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_PageRankDelta.com-lj.ungraph.gcc_6.3.0_O3.drop_3500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_PageRankDelta.com-lj.ungraph.gcc_6.3.0_O3.drop_11750M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_PageRankDelta.com-lj.ungraph.gcc_6.3.0_O3.drop_35250M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Components-Shortcut.com-lj.ungraph.gcc_6.3.0_O3.drop_11500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFSCC.com-lj.ungraph.gcc_6.3.0_O3.drop_3500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_Radii.com-lj.ungraph.gcc_6.3.0_O3.drop_24500M.length_250M.champsimtrace.xz",
    "traces/ligra/ligra_BFS.com-lj.ungraph.gcc_6.3.0_O3.drop_15750M.length_250M.champsimtrace.xz"
]

parsec_trace=[
        "traces/parsec/parsec_2.1.canneal.simlarge.prebuilt.drop_0M.length_250M.champsimtrace.xz",
        "traces/parsec/parsec_2.1.canneal.simlarge.prebuilt.drop_500M.length_250M.champsimtrace.xz",
        "traces/parsec/parsec_2.1.canneal.simlarge.prebuilt.drop_1250M.length_250M.champsimtrace.xz",
        "traces/parsec/parsec_2.1.canneal.simlarge.prebuilt.drop_3000M.length_250M.champsimtrace.xz",
        "traces/parsec/parsec_2.1.canneal.simlarge.prebuilt.drop_4500M.length_250M.champsimtrace.xz",
        "traces/parsec/parsec_2.1.canneal.simlarge.prebuilt.drop_4750M.length_250M.champsimtrace.xz",
        "traces/parsec/parsec_2.1.canneal.simlarge.prebuilt.drop_5000M.length_15M.champsimtrace.xz",
        "traces/parsec/parsec_2.1.streamcluster.simlarge.prebuilt.drop_0M.length_250M.champsimtrace.xz",
        "traces/parsec/parsec_2.1.streamcluster.simlarge.prebuilt.drop_250M.length_250M.champsimtrace.xz",
        "traces/parsec/parsec_2.1.streamcluster.simlarge.prebuilt.drop_4750M.length_250M.champsimtrace.xz",
        "traces/parsec/parsec_2.1.streamcluster.simlarge.prebuilt.drop_6250M.length_250M.champsimtrace.xz",
        "traces/parsec/parsec_2.1.streamcluster.simlarge.prebuilt.drop_14750M.length_250M.champsimtrace.xz",
        "traces/parsec/parsec_2.1.facesim.simlarge.prebuilt.drop_1500M.length_250M.champsimtrace.xz",
        "traces/parsec/parsec_2.1.facesim.simlarge.prebuilt.drop_21500M.length_250M.champsimtrace.xz",
        "traces/parsec/parsec_2.1.raytrace.simlarge.prebuilt.drop_23500M.length_250M.champsimtrace.xz",
        "traces/parsec/parsec_2.1.raytrace.simlarge.prebuilt.drop_23750M.length_250M.champsimtrace.xz"
  
]
all_traces = spec_trace + gap_trace + parsec_trace

mcore_traces_hetero=[]
suite_num = 0
for trace in all_traces:
    matches = re.match(r'traces/(.*)/(.*)',trace)
    if matches.group(1) != 'cs':
        mcore_traces_hetero.append(trace)
        mcore_traces_hetero.append(trace)
        mcore_traces_hetero.append(trace)
        mcore_traces_hetero.append(trace)
    else:
        mcore_traces_hetero.append(trace)

total_length = len(spec_trace) + len(gap_trace)+len(parsec_trace)
# Generate 90 unique random numbers within the specified range
# rand_idx1 = random.sample(range(total_length), 120)
# rand_idx1=[
#     109, 108, 107, 106, 105, 104, 103, 102, 100, 98, 97, 96, 95, 94, 93, 92, 91, 90, 
#     88, 87, 86, 85, 84, 83, 82, 81, 80, 77, 76, 75, 74, 73, 71, 70,
#      69, 68, 64, 63, 62, 61, 60, 59, 58, 57, 56, 54, 51, 50, 49, 48, 47, 46, 45, 44, 42, 40, 39, 37, 36, 35, 34, 32, 31, 30, 29, 28, 27, 25, 24, 23, 22, 21, 20, 19, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
# rand_idx = rand_idx1[::-1]
with open('4core_homogeneous2.in','w') as f:
    # for item in rand_idx:
    #     f.write(f'{item}, ')
    # f.write('\n')
    for item in range(len(all_traces)):
        f.write(f'{all_traces[item]}\n')
        f.write(f'{all_traces[item]}\n')
        f.write(f'{all_traces[item]}\n')
        f.write(f'{all_traces[item]}\n')
        f.write('\n')

rand_idx =  [random.randint(0, len(all_traces)-1) for _ in range(120*4)]
# rand_idx2 =  [random.randint(0, (math.floor(len(cs_trace)/4-1))) for _ in range(10)]
with open('4core_heterogeneous2.in','w') as f:
    i = 0
    for item in rand_idx:
        i = i+1
        f.write(f'{all_traces[item]}\n')
        if(i == 4):
            f.write('\n')
            i = 0
#     for item in rand_idx2:
#         f.write(f'{cs_trace[item*4]}\n')
#         f.write(f'{cs_trace[item*4+1]}\n')
#         f.write(f'{cs_trace[item*4+2]}\n')
#         f.write(f'{cs_trace[item*4+3]}\n')
#         f.write('\n')

